' 泳道图（Swimlane Diagram）示例
' https://plantuml.com/zh/activity-diagram-beta#dadd115c61036c7a

@startuml
' 引入通用配置
!include ./styles/swimlane_diagram.puml

' 使用管道符|来定义泳道 & 增加别名 & 定义样式
|#palegreen|user| 用户
|system| 系统
|#gold|db| 数据库


|user|
start
  :输入用户名和密码;
  -> 点击登录按钮;
  note right
    <font size=18>这是大号字体</font>
    多行内容
    <font size=10 color=red>这是小号字体</font>
  end note

|system|
  :验证用户信息;
  if (验证成功?) then (是)
    -> 生成登录凭证;
  else (否)
    -> 返回错误提示;
  endif

|db|
  :查询用户数据;

|user|
:返回查询结果;
stop

@enduml
