pipeline {
    agent {
        node {
            label 'maven'
        }
    }

    environment {
        DOCKER_REGISTRY_AUTH = "aliyun-docker-registry-auth"
        DOCKER_REGISTRY = 'registry.cn-hangzhou.aliyuncs.com/zhengqingya'
        PROJECT_GIT_URL = 'https://gitee.com/zhengqingya/small-tools.git'
        // 需要处理的服务
        SERVICE_HANDLE_LIST = ""
        K8S_NAMESPACE = "my-project"
        BASE_PROJECT_URL = "small-tools-api/"
        // TODO KubeSphere中配置流水线构建参数 => 动态传参进来
        // BRANCH_NAME = 'dev'
        // IS_SKIP_BUILD = 'false'
        // JAVA_OPTS = "-XX:+UseG1GC -Xms100m -Xmx100m -Dserver.port=8080"
        // SERVICE_NAMES = "demo,gateway"
    }

//    parameters {
//        string(name: 'BRANCH_NAME', defaultValue: 'master', description: 'git分支名')
//        string(name: 'SERVICE_NAMES', defaultValue: 'auth, gateway, demo, mall-mini, mall-web, system, tool', description: '请选择要构建的服务,英文逗号分隔')
//        choice(name: 'IS_SKIP_BUILD', choices: ['false', 'true'], description: '是否跳过构建,直接部署')
//        choice(name: 'IS_BUILD_ALL_SERVICE', choices: ['false', 'true'], description: '是否全部服务部署')
//        string(name: 'JAVA_OPTS', defaultValue: '-XX:+UseG1GC -Xms100m -Xmx100m -Dserver.port=8080', description: 'java运行参数')
//    }

    stages {

        stage('初始化准备') {
            agent none
            steps {
                container('maven') {
                    script {
                        SERVICE_HANDLE_LIST = "${SERVICE_NAMES}".split(",")
                        sh """
                            echo "分支: ${BRANCH_NAME}"
                            echo "是否跳过构建，直接部署(tips:适用于之前已经进行过构建打包的情景)：${IS_SKIP_BUILD}"
                            echo "构建运行ID: ${BUILD_NUMBER}"
                            echo "JAVA_OPTS: ${JAVA_OPTS}"
                            echo "待处理服务: ${SERVICE_HANDLE_LIST}"
                        """
                        // 镜像仓库认证
                        withCredentials([usernamePassword(credentialsId: "${DOCKER_REGISTRY_AUTH}", passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME',)]) {
                            sh 'echo "$DOCKER_PASSWORD" | docker login $DOCKER_REGISTRY -u "$DOCKER_USERNAME" --password-stdin'
                        }
                    }
                }
            }
        }

        stage('拉取代码') {
            agent none
            steps {
                container('maven') {
                    git(credentialsId: 'gitee-auth', url: "${PROJECT_GIT_URL}", branch: "${BRANCH_NAME}", changelog: true, poll: false)
                    sh 'ls -al'
                }
            }
        }

        stage('项目打包') {
            agent none
            steps {
                container('maven') {
                    script {
                        if ("${IS_SKIP_BUILD}" != "true") {
                            sh """
                                cd ${BASE_PROJECT_URL}
                                mvn clean package -Dmaven.test.skip=true
                                ls -al
                            """
                        }
                    }
                }
            }
        }

        stage('docker镜像-构建&推送') {
            agent none
            steps {
                container('maven') {
                    script {
                        if ("${IS_SKIP_BUILD}" != "true") {
                            for (service in SERVICE_HANDLE_LIST) {
                                stage("*** build&push ${service}") {
                                    def jar_dir_prefix = ""
                                    echo "****** 处理服务：${service}"
                                    switch ("${service}".trim()) {
                                        case "gateway":
                                            jar_dir_prefix = "${BASE_PROJECT_URL}/" + "${service}".trim()
                                            break
                                        case "mall-mini":
                                        case "mall-web":
                                            jar_dir_prefix = "${BASE_PROJECT_URL}/" + "service/" + "${service}".trim().split("-")[0] + "/${service}".trim()
                                            break
                                        case "demo":
                                        case "pay":
                                        case "system":
                                        case "tool":
                                        case "ums":
                                            jar_dir_prefix = "${BASE_PROJECT_URL}/service/" + "${service}".trim()
                                            break
                                    }
                                    def APP_DOCKER_IMAGE = "${DOCKER_REGISTRY}/" + "${service}".trim()
                                    sh """
                                    pwd
                                    rm -rf ${BASE_PROJECT_URL}/docker/*.jar
                                    cp ${jar_dir_prefix}/target/*.jar ${BASE_PROJECT_URL}/docker
                                    cd ${BASE_PROJECT_URL}/docker
                                    ls
                                    echo "app镜像: ${APP_DOCKER_IMAGE}"
                                    docker build -f Dockerfile --build-arg APP_NAME="${service}" --build-arg APP_PORT="8080" -t ${APP_DOCKER_IMAGE} . --no-cache
                                    docker push ${APP_DOCKER_IMAGE}
                                    echo 镜像推送成功：${APP_DOCKER_IMAGE}
                                """
                                }
                            }
                        }
                    }
                }
            }
        }


        stage('发布到k8s') {
            agent none
            steps {
                container('maven') {
                    script {
                        for (service in SERVICE_HANDLE_LIST) {
                            stage("*** deploy ${service}") {
                                println "****** 部署服务：${service}"
                                // 自定义全局变量 => 整个流水线使用
                                env.APP_NAME = "${service}"
                                env.APP_DOCKER_IMAGE = "${DOCKER_REGISTRY}/" + "${service}".trim()
                                withCredentials([kubeconfigFile(credentialsId: 'kubeconfig-auth', variable: 'KUBECONFIG')]) {
                                    if ("${service}".trim() == "gateway") {
                                        env.APP_PORT = 1218
                                        sh 'envsubst < ${BASE_PROJECT_URL}/k8s/k8s-deploy-gateway.yml | kubectl apply -f -'
                                    } else {
                                        env.APP_PORT = 8080
                                        sh 'envsubst < ${BASE_PROJECT_URL}/k8s/k8s-deploy-service.yml | kubectl apply -f -'
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }

    }
}